project:
  type: website
  output-dir: docs

website:
  title: "Kexin's Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - projects.qmd
      - volunteer.qmd
      - cv.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

